### PR TITLE
configurable expiration of retained DNS results

### PR DESCRIPTION
**Pull request by pettermahlen**
This is an alternative to #18.

### CODE REVIEW

**Comment by pettermahlen** [comment]
@pinux-studio, what do you think? Would this work?

**Comment by pinux-studio** [comment]
I don't know what magic built in to com.google.common.cache.Cache. It looks like the cache object will invalidate the value after predefined amount of time. If my understanding is correct, that is what we need. Also we set the expiration time to 2hr right?

**Comment by pettermahlen** [comment]
Guava caches are pretty magical indeed - see https://code.google.com/p/guava-libraries/wiki/CachesExplained for more info. The default is set to 2 hours in the DnsSrvResolvers class.

**Comment by pinux-studio** [comment]
:+1:

**Comment by pinux-studio** [comment]
any chance we can merge this today. I have closed mine already.

**Pull request merged**
